#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  umpnetwork:
services:

  ca0:
    image: hyperledger/fabric-ca
    container_name: ca_peerOrg1
    hostname: ca.org1.fyh.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.fyh.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5316810c59207daa8cc0cf0a84eff687259b23d372d0b867d455301d3b45a8c8_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.fyh.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/5316810c59207daa8cc0cf0a84eff687259b23d372d0b867d455301d3b45a8c8_sk -b admin:adminpw -d'
    volumes:
      - ./config/channel/crypto-config/peerOrganizations/org1.fyh.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - umpnetwork

  ca1:
    image: hyperledger/fabric-ca
    container_name: ca_peerOrg2
    hostname: ca.org2.fyh.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.fyh.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1c32e1aca45e183d1d8b7a6aef6e729c5a5c81241cb66dd224d65ac3f6d14e6d_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.fyh.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1c32e1aca45e183d1d8b7a6aef6e729c5a5c81241cb66dd224d65ac3f6d14e6d_sk -b admin:adminpw -d'
    volumes:
      - ./config/channel/crypto-config/peerOrganizations/org2.fyh.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - umpnetwork

  zookeeper0:
    container_name: zookeeper0
    hostname: zookeeper0
    image: hyperledger/fabric-zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
   
  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    image: hyperledger/fabric-zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper0:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888
    depends_on:
      - zookeeper0
      
  zookeeper2:
    container_name: zookeeper2
    hostname: zookeeper2
    image: hyperledger/fabric-zookeeper
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=0.0.0.0:2888:3888
    ports:
      - 32181:2181
      - 32888:2888
      - 33888:3888
    depends_on:
      - zookeeper0
      - zookeeper1
      
  kafka0:
    container_name: kafka0
    hostname: kafka0
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_HOST_NAME : kafka0
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: umpnetwork_default
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HOST_NAME : kafka1
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: umpnetwork_default
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 10092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      
  kafka2:
    container_name: kafka2
    hostname: kafka2
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_HOST_NAME : kafka2
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: umpnetwork_default
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 11092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      
  kafka3:
    container_name: kafka3
    hostname: kafka3
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_HOST_NAME : kafka3
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: umpnetwork_default
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 12092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
    
  orderer0.org1.fyh.com:
    hostname: orderer0.org1.fyh.com
    container_name: orderer0.org1.fyh.com
    image: hyperledger/fabric-orderer
    environment:
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_PERIOD=3s
      - ORDERER_KAFKA_RETRY_STOP=10s
      - ORDERER_KAFKA_RETRY_NETWORKTIMEOUTS_DIALTIMEOUT=30s
     
      # enabled TLS
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c "sleep 15;orderer"  
    volumes:
      - ./config/channel/channel-artifacts/:/var/hyperledger/orderer/
      - ./config/channel/crypto-config/ordererOrganizations/org1.fyh.com/orderers/orderer0.org1.fyh.com/msp:/var/hyperledger/orderer/msp
      - ./config/channel/crypto-config/ordererOrganizations/org1.fyh.com/orderers/orderer0.org1.fyh.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  orderer1.org1.fyh.com:
    hostname: orderer1.org1.fyh.com
    container_name: orderer1.org1.fyh.com
    image: hyperledger/fabric-orderer
    environment:
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      #- CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_PERIOD=3s
      - ORDERER_KAFKA_RETRY_STOP=10s
      - ORDERER_KAFKA_RETRY_NETWORKTIMEOUTS_DIALTIMEOUT=30s
     
      # enabled TLS
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c "sleep 15;orderer"  
    volumes:
    - ./config/channel/channel-artifacts/:/var/hyperledger/orderer/
    - ./config/channel/crypto-config/ordererOrganizations/org1.fyh.com/orderers/orderer1.org1.fyh.com/msp:/var/hyperledger/orderer/msp
    - ./config/channel/crypto-config/ordererOrganizations/org1.fyh.com/orderers/orderer1.org1.fyh.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 8050:7050
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  orderer2.org1.fyh.com:
    hostname: orderer2.org1.fyh.com
    container_name: orderer2.org1.fyh.com
    image: hyperledger/fabric-orderer
    environment:
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      #- CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_PERIOD=3s
      - ORDERER_KAFKA_RETRY_STOP=10s
      - ORDERER_KAFKA_RETRY_NETWORKTIMEOUTS_DIALTIMEOUT=30s
     
      # enabled TLS
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c "sleep 15;orderer"  
    volumes:
    - ./config/channel/channel-artifacts/:/var/hyperledger/orderer/
    - ./config/channel/crypto-config/ordererOrganizations/org1.fyh.com/orderers/orderer2.org1.fyh.com/msp:/var/hyperledger/orderer/msp
    - ./config/channel/crypto-config/ordererOrganizations/org2.fyh.com/orderers/orderer2.org1.fyh.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 9050:7050
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3


  orderer2.org1.fyh.com:
    hostname: orderer3.org1.fyh.com
    container_name: orderer3.org1.fyh.com
    image: hyperledger/fabric-orderer
    environment:
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      #- CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_PERIOD=3s
      - ORDERER_KAFKA_RETRY_STOP=10s
      - ORDERER_KAFKA_RETRY_NETWORKTIMEOUTS_DIALTIMEOUT=30s
     
      # enabled TLS
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c "sleep 15;orderer"  
    volumes:
    - ./config/channel/channel-artifacts/:/var/hyperledger/orderer/
    - ./config/channel/crypto-config/ordererOrganizations/org1.fyh.com/orderers/orderer3.org1.fyh.com/msp:/var/hyperledger/orderer/msp
    - ./config/channel/crypto-config/ordererOrganizations/org1.fyh.com/orderers/orderer3.org1.fyh.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 10050:7050
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  peer0.org1.fyh.com:
    container_name: peer0.org1.fyh.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=umpnetwork_default
      - CORE_LOGGING_LEVEL=DEBUG
      
      #- CORE_PEER_ENDORSER_ENABLED=true
      #- CORE_PEER_ADDRESSAUTODETECT=true
      
      - CORE_PEER_ID=peer0.org1.fyh.com
      - CORE_PEER_ADDRESS=peer0.org1.fyh.com:7051
      - CORE_PEER_NETWORKID=ump
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.fyh.com:7051
      
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
     
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./config/channel/crypto-config/peerOrganizations/org1.fyh.com/peers/peer0.org1.fyh.com/msp:/etc/hyperledger/fabric/msp
        - ./config/channel/crypto-config/peerOrganizations/org1.fyh.com/peers/peer0.org1.fyh.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - orderer0.org1.fyh.com
     
  peer1.org1.fyh.com:
    container_name: peer1.org1.fyh.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=umpnetwork_default
      - CORE_LOGGING_LEVEL=DEBUG
      
      #- CORE_PEER_ENDORSER_ENABLED=true
      #- CORE_PEER_ADDRESSAUTODETECT=true
      
      - CORE_PEER_ID=peer1.org1.fyh.com
      - CORE_PEER_ADDRESS=peer1.org1.fyh.com:7051
      - CORE_PEER_NETWORKID=ump
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.fyh.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.fyh.com:7051
      
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
     
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./config/channel/crypto-config/peerOrganizations/org1.fyh.com/peers/peer1.org1.fyh.com/msp:/etc/hyperledger/fabric/msp
        - ./config/channel/crypto-config/peerOrganizations/org1.fyh.com/peers/peer1.org1.fyh.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053
    depends_on:
      - orderer0.org1.fyh.com  
 
  peer0.org2.fyh.com:
    container_name: peer0.org2.fyh.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=umpnetwork_default
      - CORE_LOGGING_LEVEL=DEBUG
      
      #- CORE_PEER_ENDORSER_ENABLED=true
      #- CORE_PEER_ADDRESSAUTODETECT=true
      
      - CORE_PEER_ID=peer0.org2.fyh.com
      - CORE_PEER_ADDRESS=peer0.org2.fyh.com:7051
      - CORE_PEER_NETWORKID=ump
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.fyh.com:7051
      
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
     
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./config/channel/crypto-config/peerOrganizations/org2.fyh.com/peers/peer0.org2.fyh.com/msp:/etc/hyperledger/fabric/msp
      - ./config/channel/crypto-config/peerOrganizations/org2.fyh.com/peers/peer0.org2.fyh.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053
    depends_on:
      - orderer0.org1.fyh.com
    
  peer1.org2.fyh.com:
    container_name: peer1.org2.fyh.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=umpnetwork_default
      - CORE_LOGGING_LEVEL=DEBUG
      
      #- CORE_PEER_ENDORSER_ENABLED=true
      #- CORE_PEER_ADDRESSAUTODETECT=true
      
      - CORE_PEER_ID=peer1.org2.fyh.com
      - CORE_PEER_ADDRESS=peer1.org2.fyh.com:7051
      - CORE_PEER_NETWORKID=ump
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.fyh.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.fyh.com:7051
      
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
     
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./config/channel/crypto-config/peerOrganizations/org2.fyh.com/peers/peer1.org2.fyh.com/msp:/etc/hyperledger/fabric/msp
      - ./config/channel/crypto-config/peerOrganizations/org2.fyh.com/peers/peer1.org2.fyh.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10151:7051
      - 10152:7052
      - 10153:7053 
    depends_on:
      - orderer0.org1.fyh.com